"""add_guest_rate_limits_table

Revision ID: 863de1fdac93
Revises: b4e8c1f9d2a7
Create Date: 2026-09-21 15:18:57.110877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '863de1fdac93'
down_revision: Union[str, None] = 'b4e8c1f9d2a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest_rate_limits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('identifier', sa.String(length=128), nullable=False),
    sa.Column('identifier_type', sa.String(length=16), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('window_start', sa.DateTime(), nullable=False),
    sa.Column('window_expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guest_rate_limits_id'), 'guest_rate_limits', ['id'], unique=False)
    op.create_index('ix_guest_rate_limits_ident_expires', 'guest_rate_limits', ['identifier', 'window_expires_at'], unique=False)
    op.create_index(op.f('ix_guest_rate_limits_identifier'), 'guest_rate_limits', ['identifier'], unique=False)
    op.create_index(op.f('ix_guest_rate_limits_window_expires_at'), 'guest_rate_limits', ['window_expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_guest_rate_limits_window_expires_at'), table_name='guest_rate_limits')
    op.drop_index(op.f('ix_guest_rate_limits_identifier'), table_name='guest_rate_limits')
    op.drop_index('ix_guest_rate_limits_ident_expires', table_name='guest_rate_limits')
    op.drop_index(op.f('ix_guest_rate_limits_id'), table_name='guest_rate_limits')
    op.drop_table('guest_rate_limits')
    # ### end Alembic commands ###
